# Flight Price Prediction

In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
! pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\vaish\anaconda3\envs\myenv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\vaish\anaconda3\envs\myenv\Lib\site-packages (from openpyxl) (2.0.0)

In [112]:
df=pd.read_excel("C:\\Users\\vaish\\Downloads\\Data_Train (1).xlsx")

In [113]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [114]:
df.shape

(10683, 11)

In [115]:
df.describe

<bound method NDFrame.describe of            Airline Date_of_Journey    Source Destination  \
0           IndiGo      24/03/2019  Banglore   New Delhi
1        Air India       1/05/2019   Kolkata    Banglore
2      Jet Airways       9/06/2019     Delhi      Cochin
3           IndiGo      12/05/2019   Kolkata    Banglore
4           IndiGo      01/03/2019  Banglore   New Delhi
...            ...             ...       ...         ...
10678     Air Asia       9/04/2019   Kolkata    Banglore
10679    Air India      27/04/2019   Kolkata    Banglore
10680  Jet Airways      27/04/2019  Banglore       Delhi
10681      Vistara      01/03/2019  Banglore   New Delhi
10682    Air India       9/05/2019     Delhi      Cochin

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
0                  BLR → DEL    22:20  01:10 22 Mar   2h 50m    non-stop
1      CCU → IXR → BBI → BLR    05:50         13:15   7h 25m     2 stops
2      DEL → LKO → BOM → COK    09:25  04:25 10 Jun      19h     2 stops
3            CCU → NAG → BLR    18:05         23:30   5h 25m      1 stop
4            BLR → NAG → DEL    16:50         21:35   4h 45m      1 stop
...                      ...      ...           ...      ...         ...
10678              CCU → BLR    19:55         22:25   2h 30m    non-stop
10679              CCU → BLR    20:45         23:20   2h 35m    non-stop
10680              BLR → DEL    08:20         11:20       3h    non-stop
10681              BLR → DEL    11:30         14:10   2h 40m    non-stop
10682  DEL → GOI → BOM → COK    10:55         19:15   8h 20m     2 stops

      Additional_Info  Price
0             No info   3897
1             No info   7662
2             No info  13882
3             No info   6218
4             No info  13302
...               ...    ...
10678         No info   4107
10679         No info   4145
10680         No info   7229
10681         No info  12648
10682         No info  11753

[10683 rows x 11 columns]>

In [116]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [117]:
df.duplicated().sum()

np.int64(220)

In [118]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='str')

In [119]:
# data preprocessing

# drop the missing values
df.dropna(inplace=True)

In [120]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [121]:
df.duplicated().sum()

np.int64(220)

In [122]:
# drop the duplicated values

df.drop_duplicates(inplace=True)


df.duplicated().sum()

np.int64(0)

In [123]:
# handel the first column = Date_od_Journey

df["Date_of_Journey"]=pd.to_datetime(df["Date_of_Journey"],errors="coerce")

df["Day"]=df["Date_of_Journey"].dt.day
df["Month"]=df["Date_of_Journey"].dt.month
df["Year"]=df["Date_of_Journey"].dt.year

df.drop("Date_of_Journey",axis=1,inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_13348\2582859139.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Date_of_Journey"]=pd.to_datetime(df["Date_of_Journey"],errors="coerce")

In [124]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Day', 'Month',
       'Year'],
      dtype='str')

In [125]:
# drop the aditional info column
df.drop("Additional_Info",axis=1,inplace=True)
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Price', 'Day', 'Month', 'Year'],
      dtype='str')

In [126]:
# deptime column
df["Hour"]=pd.to_datetime(df["Dep_Time"]).dt.hour
df["Minute"]=pd.to_datetime(df["Dep_Time"]).dt.minute

df.drop("Dep_Time",axis=1,inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_13348\503671728.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Hour"]=pd.to_datetime(df["Dep_Time"]).dt.hour
C:\Users\vaish\AppData\Local\Temp\ipykernel_13348\503671728.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Minute"]=pd.to_datetime(df["Dep_Time"]).dt.minute

In [127]:
# arival time column
df["Arrival_Time"]=df["Arrival_Time"].str.split(" ",expand=True)[0]

df["Arrival_Time"]=pd.to_datetime(df["Arrival_Time"],errors="coerce")
df["Arr_Hour"]=pd.to_datetime(df["Arrival_Time"]).dt.hour
df["Arr_Minute"]=pd.to_datetime(df["Arrival_Time"]).dt.minute

df.drop("Arrival_Time",axis=1,inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_13348\3748869710.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Arrival_Time"]=pd.to_datetime(df["Arrival_Time"],errors="coerce")

In [130]:
# duration column
df["Duration"]=df["Duration"].str.replace("h"," ").str.replace("m"," ")

df["Duration_Hours"]=df["Duration"].str.split(" ",expand=True)[0]
df["Duration_Minutes"]=df["Duration"].str.split(" ",expand=True)[1]

df["Duration_Minutes"].fillna(0,inplace=True)

df.drop("Duration",axis=1,inplace=True)

C:\Users\vaish\AppData\Local\Temp\ipykernel_13348\1165267446.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Duration_Minutes"].fillna(0,inplace=True)

In [ ]:
# total stop column
# check uique values in the total stop column
df["Total_Stops"].unique()

# handel all values
df["Total_Stops"]=df["Total_Stops"].map({
    'non-stop':0,
    '2 stops':1,
    '1 stop':2,
    '3 stops':3,
    '4 stops':4
})

In [ ]:
# handel the route column
df["Route_1"]=df["Route"].str.split("→",expand=True)[0]
df["Route_2"]=df["Route"].str.split("→",expand=True)[1]
df["Route_3"]=df["Route"].str.split("→",expand=True)[2]
df["Route_4"]=df["Route"].str.split("→",expand=True)[3]
df["Route_5"]=df["Route"].str.split("→",expand=True)[4]

df.drop("Route",axis=1,inplace=True)

# convert the nan value to the 0 and 1

In [ ]:
#

In [137]:
df

,Airline,Source,Destination,Route,Total_Stops,Price,Day,Month,Year,Hour,Minute,Arr_Hour,Arr_Minute,Duration_Hours,Duration_Minutes,Route_1,Route_2,Route_3,Route_4,Route_5
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,3897,24,3,2019,22,20,1,10,2,,BLR,DEL,NaN,NaN,NaN
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,1,7662,1,5,2019,5,50,13,15,7,,CCU,IXR,BBI,BLR,NaN
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,1,13882,9,6,2019,9,25,4,25,19,,DEL,LKO,BOM,COK,NaN
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,2,6218,12,5,2019,18,5,23,30,5,,CCU,NAG,BLR,NaN,NaN
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,2,13302,1,3,2019,16,50,21,35,4,,BLR,NAG,DEL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0,4107,9,4,2019,19,55,22,25,2,,CCU,BLR,NaN,NaN,NaN
10679,Air India,Kolkata,Banglore,CCU → BLR,0,4145,27,4,2019,20,45,23,20,2,,CCU,BLR,NaN,NaN,NaN
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0,7229,27,4,2019,8,20,11,20,3,,BLR,DEL,NaN,NaN,NaN
10681,Vistara,Banglore,New Delhi,BLR → DEL,0,12648,1,3,2019,11,30,14,10,2,,BLR,DEL,NaN,NaN,NaN
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,1,11753,9,5,2019,10,55,19,15,8,,DEL,GOI,BOM,COK,NaN